GET http://localhost:3003/api/users
# Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmMmFhZDllODRlYTU0NjQ5NGY2ODkzYyIsImlhdCI6MTU5NjYzNjQwOH0.dSBcxffJfTWZSdoUebjr9q6gNGz3PvjLhy7yQZRTJDU
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InBpcnZhbmRyZWkiLCJpZCI6IjVmMjkxODRlYzA3NjI0NTRiOGJlNzMxMiIsImlhdCI6MTU5NjYzOTk4Nn0.NuXVmI27DFxygf3eKwnn7O6HCUJhuhS-L6Eec9FCouY
### 

POST http://localhost:3003/api/users
content-type: application/json

{
    "username" : "root",
    "password" : "root",
    "name" : "root"
} 